<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-SUVTTLO" failures="2" tests="6" name="Test Runner 2" time="0.06" errors="0" timestamp="2024-08-28T16:20:48 IST">
  <testcase classname="ParallelExecution.Test6" name="demo1" time="0.007"/>
  <testcase classname="ParallelExecution.Test6" name="demo2" time="0.001"/>
  <testcase classname="ParallelExecution.Test5" name="demo1" time="0.001"/>
  <testcase classname="ParallelExecution.Test5" name="demo2" time="0.007"/>
  <testcase classname="ParallelExecution.Test4" name="demo1" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ParallelExecution.Test4.demo1(Test4.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase classname="ParallelExecution.Test4" name="demo2" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ParallelExecution.Test4.demo2(Test4.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo2 -->
</testsuite> <!-- Test Runner 2 -->
